# Generated by Django 3.2.3 on 2021-05-30 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profilClient'),
            preserve_default=False,
        ),
    ]
