# Generated by Django 3.2.3 on 2021-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_chauffeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cni', models.ImageField(upload_to='cni')),
                ('taxi', models.ImageField(upload_to='taxi')),
                ('permi', models.ImageField(upload_to='permi')),
                ('mtrc', models.CharField(max_length=50)),
            ],
        ),
    ]
