# Generated by Django 3.2.3 on 2021-06-01 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210601_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='mtrc',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
