# Generated by Django 3.2.3 on 2021-06-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='mtrc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.taxi'),
        ),
    ]
