# Generated by Django 3.2.4 on 2021-06-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_chauffeur_mtrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='mtrc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='mtrc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.chauffeur'),
        ),
    ]
