# Generated by Django 3.2.4 on 2021-06-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_taxi_mtrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='mtrc',
            field=models.CharField(max_length=50),
        ),
    ]
