# Generated by Django 3.2.4 on 2021-06-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_taxi_mtrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderchauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('tele', models.CharField(max_length=200)),
            ],
        ),
    ]
