# Generated by Django 3.2.4 on 2021-06-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210609_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderchauffeur',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='orderchauffeur',
            name='log',
        ),
    ]
