# Generated by Django 3.2.4 on 2021-06-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_measurement_id_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchauffeur',
            name='id_client',
            field=models.CharField(default=45, max_length=200),
            preserve_default=False,
        ),
    ]
