# Generated by Django 3.2.4 on 2021-06-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_orderchauffeur_id_chofo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.CharField(max_length=200)),
                ('profilClient', models.CharField(max_length=200)),
                ('nomcl', models.CharField(max_length=200)),
                ('prenomcl', models.CharField(max_length=200)),
            ],
        ),
    ]
