# Generated by Django 3.2.4 on 2021-06-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='lat',
            field=models.CharField(default=23456, max_length=200),
            preserve_default=False,
        ),
    ]
