# Generated by Django 3.2.4 on 2021-06-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_commande_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='lng',
            field=models.CharField(default=234567, max_length=200),
            preserve_default=False,
        ),
    ]
