# Generated by Django 3.2.4 on 2021-06-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_commande_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nbrplace',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
