# Generated by Django 3.2.4 on 2021-06-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_orderchauffeur_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchauffeur',
            name='id_Commande',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
