# Generated by Django 3.2.4 on 2021-06-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_orderchauffeur_id_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchauffeur',
            name='lat',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
