# Generated by Django 3.2.4 on 2021-06-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_orderchauffeur_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchauffeur',
            name='profilCh',
            field=models.CharField(default=45, max_length=200),
            preserve_default=False,
        ),
    ]
