# Generated by Django 3.2.4 on 2021-06-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_orderchauffeur_profilch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChofoChoisir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.CharField(max_length=200)),
                ('id_chofo', models.CharField(max_length=200)),
                ('id_orderch', models.CharField(max_length=200)),
            ],
        ),
    ]
