# Generated by Django 3.2.4 on 2021-06-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_finalcmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcmd',
            name='destination',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
